#!/bin/sh

# Install Node.js dependencies
npm install

# ElasticSearch: https://www.elastic.co/downloads/past-releases/elasticsearch-2-4-3
wget https://download.elastic.co/elasticsearch/release/org/elasticsearch/distribution/tar/elasticsearch/2.4.3/elasticsearch-2.4.3.tar.gz -O es/elasticsearch.tar.gz
sha1sum es/elasticsearch.tar.gz
tar -xzf es/elasticsearch.tar.gz -C es/
mv es/elasticsearch-2.4.3 es/elasticsearch
rm es/elasticsearch.tar.gz

./es/elasticsearch/bin/plugin install mobz/elasticsearch-head



# Kibana: https://www.elastic.co/downloads/past-releases/kibana-4-6-3
git clone https://github.com/Memristor-Robotics/kibana.git es/kibana --depth=1
npm --prefix ./es/kibana install ./es/kibana

# Load Kibana settings
node src/Dumper.js --load-kibana-settings
